version: '3.8'

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://portfolio-mongodb:27017/portfolio_development
      - REDIS_URL=redis://portfolio-redis:6379
      - JWT_SECRET=your-dev-jwt-secret-key
      - LOG_LEVEL=debug
    depends_on:
      - portfolio-mongodb
      - portfolio-redis
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - portfolio-network
    restart: unless-stopped

  portfolio-mongodb:
    image: mongo:6
    container_name: portfolio-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=portfolio_development
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - portfolio-network
    restart: unless-stopped

  portfolio-redis:
    image: redis:7-alpine
    container_name: portfolio-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - portfolio-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  mongodb_dev_data:
  redis_dev_data:

networks:
  portfolio-network:
    driver: bridge